# Use postgres/example user/password credentials
version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ./volumes/postgres_data_volume:/var/lib/postgresql/data

  booking:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 5555:5555