# CASSANDRA development

version: '3'

services:
  cassandra_database:
    image: datastax/dse-server:5.1.11
    restart: always
    volumes:
      - ~/src/app/cassandra_volume:/var/lib/cassandra
      - ./db:/src/app/db

  # booking:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/Dockerfile.dev
  #   restart: always
  #   depends_on: 
  #     - cassandra_database
  #   ports:
  #     - 5555:5555
  #   volumes:
  #     - .:/src/app