# CASSANDRA production

version: '3'

services:
  database:
    image: cassandra
    restart: always
    environment:

    volumes:
      - ./volumes/cassandra_data_volume:/var/lib/postgresql/data

  booking:
    build: 
      context: .
      dockerfile: /dockerfiles/Dockerfile.prod
    restart: always
    ports:
      - 5555:5555