version: '3'

services:
  database:
    image: cassandra
    restart: always
    environment:
      # POSTGRES_PASSWORD: docker

  booking:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5555:5555