# Use postgres/example user/password credentials
version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker

  booking:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5555:5555